import type { NextPage } from 'next';
import Head from 'next/head';
import BaseTemplate from '../components/templates/base/BaseTemplate';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <BaseTemplate sampleTextProp="test" />
      </div>
    </div>
  );
};

export default Home;
